spring.application.name=landry-carroll_midterm_CEN-4802C-23594
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
logging.structured.format.console=logstash
